# Generated by Django 5.0.6 on 2024-05-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
